excluded:
  - Dangerfile.swift
  - FAKE_OBJ.swift
  - TestApps
  - SwiftDatastore

included:
  - Sources

file_length:
  warning: 400
  error: 500

cyclomatic_complexity:
  - 10 # warning
  - 11 # error

line_length:
    warning: 130
    error: 150
    ignores_comments: true

identifier_name:
  min_length:
    error: 2
  max_length:
    warning: 30
    error: 35

type_name:
  excluded:
    - T

vertical_whitespace:
  severity: error

duplicate_imports: error
force_cast: error
force_try: error

opt_in_rules:
  - switch_case_alignment
  - switch_case_on_newline
  - force_unwrapping
  - closure_spacing
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment
  - operator_usage_whitespace
  - void_return
  - unused_optional_binding
  - unused_enumerated
  - unused_closure_parameter
  - unneeded_break_in_switch
  - weak_delegate
  # - modifier_order

disabled_rules: 
  - trailing_whitespace
  - inclusive_language

reporter: "xcode"
