
ignore:
  - "SwiftDatastore/SwiftDatastoreTests"
  - "SwiftDatastore/TestApp"
  - "SwiftDatastore/TestAppTests"

comment:
  require_head: true
  layout: [reach, diff, files, header, feedback]
  behavior: "new"

coverage:
  range: 80...90
  allow_pseudo_compare: true
  allow_coverage_offsets: true

  status:
    project:
      default:
        target: 85%
        threshold: "0.5%"

    patch:
      default:
        target: 85%
        threshold: "0.5%"
