
ignore:
  - "SwiftDatastore/SwiftDatastoreTests"
  - "SwiftDatastore/TestApp"
  - "SwiftDatastore/TestAppTests"

comment:
  layout: 
    - reach
    - diff
    - files
    - header
    - feedback
  behavior: "new"

coverage:
  range: 80...90

  status:
    project:
      default:
        target: 85%
        threshold: "0.5%"

    patch:
      default:
        target: 85%
        threshold: "0.5%"
