
codecov:
  allow_pseudo_compare: true
  allow_coverage_offsets: true
  require_ci_to_pass: true
  bot: "tomkuku"

ignore:
  - "SwiftDatastore/SwiftDatastoreTests"
  - "SwiftDatastore/TestApp"
  - "SwiftDatastore/TestAppTests"

comment:
  require_base: true
  layout: "header, reach, diff, files, feedback"
  behavior: "new"

coverage:
  range: 80...90

  status:
    project:
      default:
        target: 85%
        threshold: "0.5%"

    patch:
      default:
        target: 60%
