platform :ios, '15.0'

use_frameworks!

target 'CocoaPodsApp' do

  pod 'SwiftDatastore', :git => 'https://github.com/tomkuku/SwiftDatastore.git', :tag => "0.0.5"

  target 'CocoaPodsAppTests' do
    inherit! :search_paths
  end
end