platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target 'SwiftDatastore' do
  pod 'SwiftLint', '~> 0.48.0'

  target 'SwiftDatastoreTests' do
    inherit! :search_paths

    pod 'SwiftHamcrest', '~> 2.2.2'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
