platform :ios, '15.0'

use_frameworks!

target 'DemoAppCocoaPods' do

  pod 'SwiftDatastore', :path => '..'

  target 'DemoAppCocoaPodsTests' do
    inherit! :search_paths

    pod 'SwiftHamcrest', '~> 2.2.2'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end