name: Build and Test

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

env:
  SCRIPTS_DIR: ci_scripts

jobs:  
  swift-datastore:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: |
        make -B swift_datastore
    - name: Validate codecov.yml
      run: |
        bash ${{env.SCRIPTS_DIR}}/codecov_validation.sh
    - name: Upload coverage to Codecov.io
      continue-on-error: false
      uses: codecov/codecov-action@v1.2.1
 
  test-app:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: |
        make -B test_app

  cocoa-pods-test-app:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pod Install
      run: |
        pod install --project-directory='TestApps/CocoaPodsApp'
    - name: Build
      run: |
        make -B cocoa_pods_test_app

  spm-test-app:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        make -B spm_test_app
